<a href="https://colab.research.google.com/github/EZZRITOE/cookie-recipe/blob/master/Copy_of_Moringa_Data_Science_Prep_W4_Independent_Project_2019_07_Ezra_Mageto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  1.0 Importing our Libraries

In [3]:
# Importing the libraries we will need 

# Importing the pandas library
# 
import pandas as pd

# Importing the numpy library
#
import numpy as np

#1.1 Reading the Dataset from CSV file

In [4]:
#Read data from CSV file
link= 'http://bit.ly/autolib_dataset'
df=pd.read_csv(link,index_col=0)
df

                                    Cars  Bluecar counter  ...  hour  minute
Address                                                    ...
2 Avenue de Suffren                    0                0  ...    11      43
145 Rue Raymond Losserand              6                6  ...     7      24
2 Avenue John Fitzgerald Kennedy       3                3  ...    20      14
51 Rue EugÃ¨ne OudinÃ©                 3                3  ...     4      37
6 avenue de la Porte de Champerret     3                3  ...    17      23
...                                  ...              ...  ...   ...     ...
8 avenue MÃ©nelotte                    2                2  ...    11      26
37 rue de Dantzig                      4                4  ...    16      56
142 rue du Bac                         1                1  ...     7       1
2 avenue du Val de Fontenay            2                2  ...    17      27
5 Rue Henry Brisson                    4                4  ...    10       2

[5000 rows x 24 columns]

#1.2 Previewing the Dataset

In [5]:
df.head()

                                    Cars  Bluecar counter  ...  hour  minute
Address                                                    ...
2 Avenue de Suffren                    0                0  ...    11      43
145 Rue Raymond Losserand              6                6  ...     7      24
2 Avenue John Fitzgerald Kennedy       3                3  ...    20      14
51 Rue EugÃ¨ne OudinÃ©                 3                3  ...     4      37
6 avenue de la Porte de Champerret     3                3  ...    17      23

[5 rows x 24 columns]

In [6]:
df.tail()

                             Cars  Bluecar counter  ...  hour  minute
Address                                             ...
8 avenue MÃ©nelotte             2                2  ...    11      26
37 rue de Dantzig               4                4  ...    16      56
142 rue du Bac                  1                1  ...     7       1
2 avenue du Val de Fontenay     2                2  ...    17      27
5 Rue Henry Brisson             4                4  ...    10       2

[5 rows x 24 columns]

In [7]:
# checking data types information
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 2 Avenue de Suffren to 5 Rue Henry Brisson
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Cars                 5000 non-null   int64
 1   Bluecar counter      5000 non-null   int64
 2   Utilib counter       5000 non-null   int64
 3   Utilib 1.4 counter   5000 non-null   int64
 4   Charge Slots         5000 non-null   int64
 5   Charging Status      5000 non-null   object
 6   City                 5000 non-null   object
 7   Displayed comment    111 non-null    object
 8   ID                   5000 non-null   object
 9   Kind                 5000 non-null   object
 10  Geo point            5000 non-null   object
 11  Postal code          5000 non-null   int64
 12  Public name          5000 non-null   object
 13  Rental status        5000 non-null   object
 14  Scheduled at         47 non-null     object
 15  Slots                5000 non-null   int64
 16  Station type         5000 non-null   object
 17  Status               5000 non-null   object
 18  Subscription status  5000 non-null   object
 19  year                 5000 non-null   int64
 20  month                5000 non-null   int64
 21  day                  5000 non-null   int64
 22  hour                 5000 non-null   int64
 23  minute               5000 non-null   int64
dtypes: int64(12), object(12)
memory usage: 976.6+ KB

In [8]:
df.columns
#checking the columns in the dataset

Index(['Cars', 'Bluecar counter', 'Utilib counter', 'Utilib 1.4 counter',
       'Charge Slots', 'Charging Status', 'City', 'Displayed comment', 'ID',
       'Kind', 'Geo point', 'Postal code', 'Public name', 'Rental status',
       'Scheduled at', 'Slots', 'Station type', 'Status',
       'Subscription status', 'year', 'month', 'day', 'hour', 'minute'],
      dtype='object')

In [9]:
#enhancing completeness and checking missing values from each column
df.isnull().sum()

Cars                      0
Bluecar counter           0
Utilib counter            0
Utilib 1.4 counter        0
Charge Slots              0
Charging Status           0
City                      0
Displayed comment      4889
ID                        0
Kind                      0
Geo point                 0
Postal code               0
Public name               0
Rental status             0
Scheduled at           4953
Slots                     0
Station type              0
Status                    0
Subscription status       0
year                      0
month                     0
day                       0
hour                      0
minute                    0
dtype: int64

In [10]:
df.notnull().sum()

Cars                   5000
Bluecar counter        5000
Utilib counter         5000
Utilib 1.4 counter     5000
Charge Slots           5000
Charging Status        5000
City                   5000
Displayed comment       111
ID                     5000
Kind                   5000
Geo point              5000
Postal code            5000
Public name            5000
Rental status          5000
Scheduled at             47
Slots                  5000
Station type           5000
Status                 5000
Subscription status    5000
year                   5000
month                  5000
day                    5000
hour                   5000
minute                 5000
dtype: int64

In [11]:
#drop columns with missing values


df = df.drop([ 'Displayed comment',  'Scheduled at'], axis=1)
df.head()

                                    Cars  Bluecar counter  ...  hour  minute
Address                                                    ...
2 Avenue de Suffren                    0                0  ...    11      43
145 Rue Raymond Losserand              6                6  ...     7      24
2 Avenue John Fitzgerald Kennedy       3                3  ...    20      14
51 Rue EugÃ¨ne OudinÃ©                 3                3  ...     4      37
6 avenue de la Porte de Champerret     3                3  ...    17      23

[5 rows x 22 columns]

In [12]:
#checking  duplicate columns
df.duplicated()

Address
2 Avenue de Suffren                   False
145 Rue Raymond Losserand             False
2 Avenue John Fitzgerald Kennedy      False
51 Rue EugÃ¨ne OudinÃ©                False
6 avenue de la Porte de Champerret    False
                                      ...
8 avenue MÃ©nelotte                   False
37 rue de Dantzig                     False
142 rue du Bac                        False
2 avenue du Val de Fontenay           False
5 Rue Henry Brisson                   False
Length: 5000, dtype: bool

In [13]:
#drop duplicate columns
df.drop_duplicates()

                                    Cars  Bluecar counter  ...  hour  minute
Address                                                    ...
2 Avenue de Suffren                    0                0  ...    11      43
145 Rue Raymond Losserand              6                6  ...     7      24
2 Avenue John Fitzgerald Kennedy       3                3  ...    20      14
51 Rue EugÃ¨ne OudinÃ©                 3                3  ...     4      37
6 avenue de la Porte de Champerret     3                3  ...    17      23
...                                  ...              ...  ...   ...     ...
8 avenue MÃ©nelotte                    2                2  ...    11      26
37 rue de Dantzig                      4                4  ...    16      56
142 rue du Bac                         1                1  ...     7       1
2 avenue du Val de Fontenay            2                2  ...    17      27
5 Rue Henry Brisson                    4                4  ...    10       2

[5000 rows x 22 columns]

#1.3 Research Question

In [14]:

#Identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018
car = df.groupby(['hour'])['Bluecar counter'].sum()
car.head()

hour
0    483
1    493
2    559
3    549
4    512
Name: Bluecar counter, dtype: int64

In [15]:
#Question:What postal code is the most popular for picking up Blue cars?
df.groupby(['Postal_code','hour'])['bluecar_counter'].sum().sort_values(ascending = False).head()
df

KeyError: ignored